version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/longkey1/diary
    steps:
      - checkout
      - restore_cache:
          key: v1-pkg-cache-{{ checksum "Gopkg.lock" }}
      - run: go get -u github.com/golang/dep/cmd/dep
      - run: dep ensure
      - save_cache:
          key: v1-pkg-cache-{{ checksum "Gopkg.lock" }}
          paths:
            - vendor
  release:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/longkey1/diary
    steps:
      - checkout
      - restore_cache:
          key: v1-pkg-cache-{{ checksum "Gopkg.lock" }}
      - run: go get -u github.com/mitchellh/gox
      - run: gox --osarch "darwin/amd64 linux/amd64 windows/amd64" --output "dist/{{.Dir}}_{{.OS}}_{{.Arch}}"
      - run: go build -o ./bin/diary
      - run: go get -u github.com/tcnksm/ghr
      - run: ghr -t $GITHUB_TOKEN -u $CIRCLE_USERNAME -r $CIRCLE_PROJECT_REPONAME v$(./bin/diary --version | cut -d " " -f 3) dist/
workflows:
  version: 2
  build_and_release:
    jobs:
      - build
      - release:
          requires:
            - build
          filters:
            branches:
              only: master
